version: "3.1"
services:

    mariadb:
        image: 'mariadb:latest'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=commercialpage
            - MYSQL_USER=local
            - MYSQL_PASSWORD=local
        ports:
            - '4004:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '21000:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'

    phpmyadmin:
      image: phpmyadmin
      ports:
        - 8083:80
      restart: 'no'
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=commercialpage
        - MYSQL_USER=local  
        - MYSQL_PASSWORD=local
        - PMA_HOST=mariadb     

